### ISSUE TITLE
Anybody test the Query performance?

### ISSUE THREAD

**Issue by GF-Huang** [ip2location/ip2location-dotnet#4]
I had try benchmark with this library, but seems it does not build by `release` mode.

![image](https://user-images.githubusercontent.com/4510984/115795978-877e7180-a403-11eb-99d4-99bbde2dc3be.png)

**Comment by ip2location-com** [comment]
Yes, we have tested the query performance and it's being used by many of our customers without issues.

**Comment by GF-Huang** [comment]
But why not build a release mode NuGet package?

**Comment by ip2location-com** [comment]
We usually build in debug mode to enable our users to easily fix integration issues with our component. If you're worried about performance, you can enable the MemoryMappedFile mode as long as your server has sufficient RAM. That will greatly speed up queries.

**Comment by GF-Huang** [comment]
I plan to use it on the client. How much memory does `MemoryMappedFile` take up? Will it increase over time?

**Comment by ip2location-com** [comment]
The MemoryMappedFile will use up about the same size as the BIN file you're querying. Your system will need to have free contiguous RAM of that size for this mode to work. No, the size does not increase over time.
