### ISSUE TITLE
Passing streams instead of database path

### ISSUE THREAD

**Issue by andriwandres** [ip2location/ip2location-dotnet#9]
I would like there to be more ways to provide the BIN Data File. 
Having to pass a File-System Path prevents me from:
1. Storing the file on another system (e.g minIO or any external file storage system)
2. Provide a caching mechanism to reduce reads to the file
3. Unit Testing & Mocking integrations with the library

Optimally, you would be able to pass a `Stream` representing the BIN file. This can be stored whereever the consumer wants. As long as you pass a valid Stream alongside with an IP adress.

In C#, I would design the following public API for loading a location result. This is not based on any existing API's but more of a rough design aproach, that I would've gone with.

```csharp
public interface IIPLocationService
{
  // Equivalent of current "IPQuery()" implementation with "IPDatabasePath"
  IPResult Query(string ipAdress, string databasePath);

  // Synchronous/Asynchronous implementation receiving a stream of the BIN file
  IPResult Query(string ipAdress, Stream binaryDatabaseStream);
  Task<IPResult> QueryAsync(string ipAdress, Stream binaryDatabaseStream);
}
```

Since you already use FileStreams to load the BIN File in `LoadBIN()`, you should be able to create an alternative way of passing an undisposed Stream and parsing the file that way.

This could potentially also be done asynchronously.

**Comment by ip2location-com** [comment]
Thank you for your suggestion. At present, we don't have any plans to include such a feature. But it is something we can consider for future development.

**Comment by ip2location-com** [comment]
FYI, we've just added support for reading a stream as well as the async IP query.
